name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: 2.1.5
  cupertino_icons: ^0.1.3
  image_picker: 0.6.3+1
  dio: 3.0.8
  path_provider: 1.6.0
  permission_handler: 4.2.0+hotfix.3
  flutter_downloader: ^1.4.1
  download_manager: 1.0.1+2
  http: 0.12.0+4
  auto_size_text: 2.1.0
  rxdart: 0.23.1
  fluttertoast: 3.1.0
  intl: ^0.15.7
  flutter_uploader: 1.2.0
  progress_dialog: 1.2.0
  pulltorefresh_flutter: 0.1.9
  flutter_easyrefresh: 2.0.9
  open_file: ^3.0.1
  file_picker: ^1.4.3+2
  shared_preferences: 0.5.6+2
  tip_dialog: 3.1.0








dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/folder.png
    - assets/images/image.png
    - assets/images/ppt.png
    - assets/images/word.png
    - assets/images/excel.png
    - assets/images/txt.png
    - assets/images/file.png
    - assets/images/zip.png
    - assets/images/mp3.png
    - assets/images/mp4.png
    - assets/images/psd.png
    - assets/images/unknown.png
    - assets/images/image.png
    - assets/images/gif.png
    - assets/images/apk.png
    - assets/images/js.png
    - assets/images/css.png
    - assets/images/html.png
    - assets/images/svg.png
    - assets/images/pdf.png
    - assets/images/jpg.png
    - assets/images/png.png
    - assets/images/python.png
    - assets/images/java.png
    - assets/images/shell.png
    - assets/images/bin.png
    - assets/images/csv.png
    - assets/images/yaml.png
    - assets/images/rar.png



  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
